name: Uptime Check

on:
  schedule:
    - cron: '*/14 * * * *'  # Runs every 14 minutes

jobs:
  ping_site:
    runs-on: ubuntu-latest
    steps:
      - name: Check the site
        id: check
        uses: srt32/uptime@master
        with:
          url-to-hit: "https://www.vegetablesking.in/"  # Replace with your website URL
          expected-statuses: "200,301"  # Adjust based on expected responses
