name: Check Site Uptime

on:
  schedule:
    # Runs the check every 15 minutes
    - cron: '*/15 * * * *'

jobs:
  check-uptime:
    runs-on: ubuntu-latest

    steps:
      - name: Check site status
        run: |
          # Replace with your website URL
          URL="https://yourwebsite.com" 
          STATUS=$(curl -o /dev/null -s -w "%{http_code}\n" $URL)
          echo "Status code: $STATUS"
          if [ "$STATUS" -ne 200 ]; then
            echo "Your site is down! Status code: $STATUS"
            exit 1
          fi
