name: Uptime Check

on:
  schedule:
    - cron: '*/14 * * * *'  # Runs every 14 minutes
  workflow_dispatch:  # Allows manual triggering of the workflow

jobs:
  ping_site:
    runs-on: ubuntu-latest
    steps:
      - name: Display Current Date and Time
        run: |
          echo "Current Date and Time: $(date)"
          echo "Next Scheduled Run: $(date -d '+14 minutes')"

      - name: Check the site
        id: check
        uses: srt32/uptime@master
        with:
          url-to-hit: "https://www.vegetablesking.in/"  # Replace with your website URL
          expected-statuses: "200,301"  # Adjust based on expected responses

      - name: Log Check Result
        run: |
          if [[ "${{ steps.check.outputs.status }}" == "200" ]]; then
            echo "Website is UP!"
          else
            echo "Website is DOWN! Status: ${{ steps.check.outputs.status }}"
          fi
